### ISSUE TITLE
bug: usePrepareContractWrite error when disabled

### ISSUE THREAD

**Issue by soccerarenadev** [wagmi-dev/wagmi#1098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.3

### Current Behavior

Using the usePrepareContractWrite hook, even if the "enabled" parameter is set to false, it returns an error.
In this case, I pass no parameter as  enabled is set to false.

<img width="565" alt="image" src="https://user-images.githubusercontent.com/99416733/196054010-79fb20c4-2a42-406a-80d5-67cbd7c3a80b.png">

### Expected Behavior

Not being an error as is set to disabled.

**Comment by jxom** [comment]
It could be because the result is cached, so it is returning the cached result (error) instead of fetching again. `wagmi` uses React Query internally as our caching layer – you can read on this behavior [here](https://tanstack.com/query/v4/docs/guides/disabling-queries). You may need to opt-out of this behaviour using `internal.isFetchedAfterMount` flag returned from `usePrepareContractWrite`.
