### ISSUE TITLE
bug: MetamaskConnector tries to connect to Core Wallet

### ISSUE THREAD

**Issue by elizalucas** [wagmi-dev/wagmi#1134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.5

### Current Behavior

I am trying to connect to MetaMask using `MetaMaskConnector`. I have the MetaMask browser extension and the Core Wallet browser extension, and the connector tries to connect to the Core Wallet.

<img width="366" alt="Screen Shot 2022-10-21 at 3 45 28 PM" src="https://user-images.githubusercontent.com/38088920/197277112-22d8734b-982d-42a0-bfbd-ee4c50a75d2b.png">

Note: I am NOT using the general `InjectedConnector` connector

### Expected Behavior

It should connect to MetaMask wallet

### Steps To Reproduce

1. Download both the MetaMask and Core Wallet browser extensions (on chrome)
2. Use `MetaMaskConnector` and connect to wallet

**Comment by jxom** [comment]
`connector.ready` seems to evaluate to falsy for me when I attempt to reproduce this on `wagmi@0.7.5` (expected result), do you think you could share a minimal reproducible example? I can reopen when so!

Here is a template: https://codesandbox.io/s/bitter-wind-pv0hwj

**Comment by elizalucas** [comment]
> `connector.ready` seems to evaluate to falsy for me when I attempt to reproduce this on `wagmi@0.7.5` (expected result), do you think you could share a minimal reproducible example? I can reopen when so!
> 
> Here is a template: https://codesandbox.io/s/bitter-wind-pv0hwj

Do you mean that MetaMask's `connector.ready` should be falsy when both Metamask and Core Wallet are installed in the browser?

**Comment by elizalucas** [comment]
Following up here - Do you mean that MetaMask's `connector.ready` should be falsy when both Metamask and Core Wallet are installed in the browser? I would expect that Metamask's `connector.ready` should be truthy as long as MetaMask extension is downloaded on the browser. 

If that's not the case, why is that?

**Comment by jxom** [comment]
Sorry about the late response! I completely missed your previous message.

Due to the nature of wallet injection in the browser, only one wallet can be injected to `window.ethereum` at a time. In this case, Core Wallet is taking precedence over MetaMask, so `window.ethereum` is populated with Core Wallet's ethereum provider. Unfortunately, there is yet to be a mature abstraction for multiple injected providers (though, there is an [EIP for this](https://github.com/ethereum/EIPs/pull/5749)).

As a result, `MetaMaskConnector`'s `connector.ready` will evaluate to falsy as `window.ethereum` does not belong to MetaMask.
