### ISSUE TITLE
bug: useBalance and useEnsAvatar still using addressOrName

### ISSUE THREAD

**Issue by carlbarrdahl** [wagmi-dev/wagmi#1135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.5

### Current Behavior

I would expect useBalance and useEnsAvatar to use `address` like the other hooks like this:
```js
 const balance = useBalance({
  address: '0xA0Cf798816D4b9b9866b5330EEa46a18382f251e',
})
```

**Comment by jxom** [comment]
Thanks for reporting! 

Definitely agree that we should converge all the hooks to use `address`, instead of having a mixture of both `address` & `addressOrName`. 

If we were to change this API now, it would be a breaking change. So we can refactor this soon & ship this one in the next breaking release (whenever that may be). 

Going to close this for now, but flag this issue as a candidate for a `0.8` change.
