### ISSUE TITLE
bug: usePrepareSendTransaction returns error even if enabled: false

### ISSUE THREAD

**Issue by ArtemFokin** [wagmi-dev/wagmi#1247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.9

### Current Behavior

Hello
i just copy example code with enabled:false and got an error
```typescript
const {error, data} = usePrepareSendTransaction({
    request: {
      to: contract,
      value: utils.parseEther("0"),
    },
    enabled: false,
  });
```
error code: `UNPREDICTABLE_GAS_LIMIT`
I know what it's about zero value, but why it's even happened if enabled:false 

### Expected Behavior

Do not throw any errors if enabled:false

**Comment by tmm** [comment]
Just tried out the code snippet you shared and was not able to reproduce the issue.  (I substituted a different address from `contract` since you did not share the value.)

Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
