### ISSUE TITLE
useWaitForTransaction never errors

### ISSUE THREAD

**Issue by tae100k** [wagmi-dev/wagmi#1264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.7

### Current Behavior

- Like this guy said (https://github.com/wagmi-dev/wagmi/discussions/428#discussioncomment-2730175)
Im not sure if i am doing something wrong, but while using useWaitForTransaction and submitting a transaction that I expect to fail, I can never catch the error? I can see the error failing on rinkeby, but useWaitForTransaction always succeeds

I have exact same issue.

And the answer said just check data.status.
-> but I needed to show different error message upto error status.

What could I do in my case?

### Expected Behavior

I need to see the error of transaction result

### Steps To Reproduce

.

### Anything else?

.

**Comment by devglrd** [comment]
Hi, same here

**Comment by 0xJax** [comment]
Same here

**Comment by tmm** [comment]
`useWaitForTransaction` `onError`/`isError`/`status === 'error'` reflect the HTTP network state (e.g. HTTP request failed) versus EVM network state (e.g. transaction failed to mine). You should inspect the data from `onSuccess` to find out if the transaction failed. `data` is an ethers [`TransactionReceipt`](https://docs.ethers.io/v5/api/providers/types/#providers-TransactionReceipt) with `status=1` if successful or `status=0` if it was reverted. (There's a note about this on the docs site [here](https://wagmi.sh/docs/hooks/useWaitForTransaction#onerror-optional).)

Appreciate the feedback. Will look into updating this behavior in the future since it seems confusing for folks.

**Comment by devglrd** [comment]
Hi @tmm, thanks for your reply.

But when a smart contract return failed with a specific message ( the required in smart contract) how to get access to this message ?

Like : 
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/26745182/201102954-03f06e13-93cf-41b8-8423-84fee3bcfbb0.png">

**Comment by Illyism** [comment]
@jxom I'm not able to grab the error messages from the waitForTransaction like the user above. Any ideas? I know with Ethers directly they are available.
