### ISSUE TITLE
bug: injected connector always opens MetaMask extension

### ISSUE THREAD

**Issue by SurenAvagyanG** [wagmi-dev/wagmi#1339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.8.5

### Current Behavior

I have chrome extensions for MetaMask wallet and BitKeep wallet. Whenever I use InjectedConnector, MetaMask is always opened, I am unable to open BitKeep. The only way to open BitKeep is to disable MetaMask extension through chrome extensions manager. I tried giving InjectedConnector constructor options object with `name: 'BitKeep'`, but it does nothing.

### Expected Behavior

I should be able to open my preferred wallet using InjectedConnector, instead of always using MetaMask

### Steps To Reproduce

- Download chrome extension for MetaMask, set up a MetaMask wallet
- Download chrome extension for BitKeep, set up a BitKeep wallet
- Use InjectedConnector
- Use SiweMessage to create a message
- Use signMessageAsync with the created message

### Anything else?

It looks like MetaMask is overwriting window.ethereum written by BitKeep. Because of this BitKeep is always ignored.

**Comment by tmm** [comment]
Due to the nature of wallet injection in the browser, only one wallet can be injected to `window.ethereum` at a time. In this case, MetaMask is taking precedence over BitKeep, so `window.ethereum` is populated with MetaMask's ethereum provider.

Unfortunately, there is yet to be a mature abstraction for multiple injected providers. There is an [EIP for this](https://github.com/ethereum/EIPs/pull/5749)) and we are also looking into a potential shim to fix this behavior.

**Comment by matewilk** [comment]
+1 to this,

When I started writing my app with `ethers.js` and wrote my own hooks, having multiple wallets in the browser, whenever I initiated the connection in the pop-up browser window I could choose which wallet I wanted to connect to.
I had MetaMask and Coinbase. Haven't tested with other though, but I'd imaging it would be similar.

**Comment by gengbingbing** [comment]
I have the same problem. Is there a solution?

**Comment by jxom** [comment]
Please see the above comment: https://github.com/wagmi-dev/wagmi/issues/1339#issuecomment-1322399074.
