### ISSUE TITLE
bug: broken useEnsName hook?

### ISSUE THREAD

**Issue by JackBDart** [wagmi-dev/wagmi#1400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.15

### Current Behavior

onSuccess, onError, and onSettled do not log anything when added to the hook. The value of isFetched never changes (tested logging every second for around 2 minutes, value remained false the entire time)

### Expected Behavior

onSuccess, onError, and onSettled should log something like the docs indicate, https://wagmi.sh/react/hooks/useEnsName#onsuccess-optional

### Steps To Reproduce

  const ensName = useEnsName({
    address: '0xA0Cf798816D4b9b9866b5330EEa46a18382f251e',
    onSuccess(data) {
      console.log('Success', data);
    },
    onError(error) {
      console.log('Error', error);
    },
    onSettled(data, error) {
      console.log('Settled', { data, error });
    },
  });
  
  doesn't log anything. It also does not successfully fetch the ens name on the first render. If a use effect hook is used to grab some piece of data and the component re-renders, then the ensName will successfully resolve.

**Comment by jxom** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via a CodeSandbox (feel free to use [this template](https://codesandbox.io/s/bitter-wind-pv0hwj)). I'll reopen when one is provided!
