### ISSUE TITLE
Wagmi packages not working. @wagmi/core says deprecated on npm

### ISSUE THREAD

**Issue by Sprimage** [wagmi-dev/wagmi#1418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

"wagmi": "^0.8.6",

### Current Behavior

Both wagmi and @wagmi core won't work. Seems @walletconnect dependency is broken

**Comment by jxom** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) in a separate repository and post it here. You can use `npm init wagmi` to scaffold a minimal wagmi app. Will reopen once a reproduction is included.
