### ISSUE TITLE
bug: metamask does not connect when both metamask and metamask institutional are installed

### ISSUE THREAD

**Issue by joshg47** [wagmi-dev/wagmi#1482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.0

**Comment by jxom** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via a CodeSandbox (feel free to use [this template](https://codesandbox.io/s/bitter-wind-pv0hwj)) and reopen this issue.
