### ISSUE TITLE
bug: AssersionError 

### ISSUE THREAD

**Issue by gaszlla** [wagmi-dev/wagmi#1537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.9.4

### Current Behavior

I have installed wagmi@0.9.4 with node 16 on react. When I compile the code, it gives the following error

`./node_modules/wagmi/dist/index.js
AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

'??' !== '||'
    at Array.forEach (<anonymous>)`

**Comment by jxom** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via a CodeSandbox (feel free to use [this template](https://codesandbox.io/s/bitter-wind-pv0hwj)). Will reopen when one is provided.

**Comment by salvaDalle** [comment]
hi, I have the same issue. what is the solution?
