### ISSUE TITLE
 error  in ./node_modules/@wagmi/connectors/dist/chunk-LBCJHW4Y.jsbug: <title>

### ISSUE THREAD

**Issue by superjiangs** [wagmi-dev/wagmi#1617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.8.10

### Current Behavior

Module parse failed: Unexpected token (61:25)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       return "MetaMask";

### Expected Behavior

No error reporting

### Steps To Reproduce

vue npm run dev

### Anything else?

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/26242617/210752115-054f9e7a-1cd7-407d-85a5-c6640e381c4f.png">
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/26242617/210752166-ed96323a-0981-42b0-89c3-e82e7e8c2c66.png">

**Comment by jxom** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via a CodeSandbox (feel free to use [this template](https://codesandbox.io/s/bitter-wind-pv0hwj)) and reopen this issue. Other information is also helpful, like framework (e.g. Next.js), browser, etc.

**Comment by superjiangs** [comment]
This problem occurs in vue2. After the dependency is downloaded, it cannot run

**Comment by silsuer** [comment]
Same issue. Is there any solution?
