### ISSUE TITLE
bug: onConnect / onDisconnect randomly not called 

### ISSUE THREAD

**Issue by NBMSacha** [wagmi-dev/wagmi#1698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.8.6

### Current Behavior

onConnect isn't triggered sometimes while it should - especially when moving from one page to another, then trying to connect.

### Expected Behavior

onConnect should be called each time user connects.

### Steps To Reproduce

- Go to mobula.fi
- Click on the gift icon
- Click on connect

**Comment by tmm** [comment]
While wagmi is in beta (versions less than 1.0.0), we only fix security-related issues from previous versions. Check out the [migration guide](https://wagmi.sh/react/migration-guide) to upgrade to the latest wagmi beta (0.10.x as of right now). If this issue is still present, please re-open this issue with a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and we can take a look.

**Comment by NBMSacha** [comment]
Still happening on 0.10, just upgraded. Will try to get a minimal reproducible example tomorrow.

**Comment by tmm** [comment]
Great! Might be captured by https://github.com/wagmi-dev/wagmi/pull/1679, but minimal example will be good as well.

**Comment by NBMSacha** [comment]
OK, just found out. Posting here as I'm pretty sure anyone can run into this, and spent nearly 3 hours to find out.

- NEVER ADD createClient INSIDE A COMPONENT

Basically it creates HUGE errors with Nextjs and components lifecycles, as the provider isn't rerendered sometimes on new pages, etc.
