### ISSUE TITLE
bug:  Cannot disable `useContractRead` by setting the enabled field to false

### ISSUE THREAD

**Issue by Joshuajee** [wagmi-dev/wagmi#1765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.10.14

### Current Behavior

When I set the `enable` field in the `useContractRead` hook to `false`, the hooks still run and read data from the blockchain

### Expected Behavior

I expected that when I set the `enable` field to false that the hook won't read data from the blockchain, I expected that this field is a way to run the hook conditionally.

### Steps To Reproduce

```js
import { useContractRead } from 'wagmi'

function App() {
 const contractRead = useContractRead({
 address: '0xecb504d39723b0be0e3a9aa33d646642d1051ee1',
 abi: wagmigotchiABI,
 functionName: 'getSleep',
 enabled: false,
 })
}
```

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

Note: The data might be cached so it returns a value for `data`, but isn't actually performing requests.

**Comment by Joshuajee** [comment]
You are right it was cached.
