### ISSUE TITLE
useContractEvent type signature incomplete?

### ISSUE THREAD

**Issue by naps62** [wagmi-dev/wagmi#1829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.5

### Current Behavior

For an event `Incremented(uint256 from, uint256 to)`, the following code works but throws a typescript warning:

```typescript
  useCounterIncrementedEvent({
    listener(from: BigNumber, to: BigNumber, receipt: any): void {
      setList([...list, { from, to, block: receipt.blockNumber }]);
    },
  });
```

The warning is `Type '(from: BigNumber, to: BigNumber, receipt: any) => void' is not assignable to type '(args_0: BigNumber, args_1: BigNumber) => void'`

### Expected Behavior

Since the code works, I assume the listener is correctly implemented, and just not fully typed? Or is there an alternative approach I should be using to get the extra data from the event?

### Anything else?

Using the latest releases from both wagmi and wagmi/cli

**Comment by tmm** [comment]
The types are correct! The receipt being present is a coincidence. ethers returns the receipt, but we don't want to encourage using it from here since [`eth_getTransactionReceipt`](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_gettransactionreceipt) is a separate RPC request. If you want to access it, you should use `provider.getTransactionReceipt`.
