### ISSUE TITLE
bug: npm i wagmi immediately produces 6 high severity vulnerabilities

### ISSUE THREAD

**Issue by scotthconner** [wagmi-dev/wagmi#1927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

the Wagmi NPM library is using a deprecated version of wallet connect, and it produces multiple high severity vulnerabilities. It would be great if using wagmi produced a clean build such that auditors won't balk at the dependency tree. It doesn't seem as though there is an easy way to upgrade to v2 SDK for wallet connect.

### Expected Behavior

I would expect the latest wagmi npm package not to be using deprecated packages.

**Comment by jxom** [comment]
These vulnerabilities exist in the Connectors I believe, which we can't really do anything about because they are downstream dependencies. It might be worth opening up issues on their repositories.

Connectors belong in their respective entrypoints (ie. `wagmi/connectors/*`), so if you don't import the Connector that has these vulnerabilities, you'll be all good. The main `wagmi` entrypoint does not have vulnerabilities.

Also, we will be removing the WalletConnect v1 Connector once it is completely deprecated (June 28).
