### ISSUE TITLE
bug: useContractWrite doesn't switch to target chain, docs state otherwise

### ISSUE THREAD

**Issue by theshadowagent** [wagmi-dev/wagmi#1967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.8.6

### Current Behavior

Docs for [useContractWrite](https://wagmi.sh/react/hooks/useContractWrite) state that if `chainId` is specified, `wagmi` will prompt the user to switch to target chain.

<img width="892" alt="image" src="https://user-images.githubusercontent.com/22137836/223480391-867be75a-505a-48f6-ad45-650c6f149b11.png">

Currently, it doesn't prompt the user to switch the chain, instead, it throws `ChainMismatchError`. If you use `usePrepareWriteContract`, the error will be thrown there. 

After looking at the code in `main`, I can confirm the error is still thrown in `assertActiveChain()` and not handled on the latest version.

### Expected Behavior

I expected the chain to change before `contractWrite` if a specific `chainId` is specified, as the docs state. Or, the docs should correctly explain the new behavior.

**Comment by jxom** [comment]
Yep. Docs should be updated.

**Comment by jxom** [comment]
Fixed.

**Comment by theshadowagent** [comment]
Is there any reason why you choose to not go with auto-switching?

**Comment by tmm** [comment]
We used to have this behavior (https://github.com/wagmi-dev/wagmi/pull/611 https://github.com/wagmi-dev/wagmi/pull/622), but removed it in https://github.com/wagmi-dev/wagmi/pull/940 since it caused issues across wallets and platforms. For example, it might work well when using desktop MetaMask, but once you start using mobile (e.g. iOS), WalletConnect, etc. mobile universal links start to expire, support for chain switching drops, and more. It also coupled some internal logic that can happen in userland so removing it end up with much more robust, maintainable code.

**Comment by zkSoju** [comment]
It looks like the docs still say that it does here:

https://wagmi.sh/react/hooks/useContractWrite#chainid-optional

**Comment by tmm** [comment]
Then we should update that :)

**Comment by tmm** [comment]
https://github.com/wagmi-dev/wagmi/commit/c02fd1caab61c93c41c8f2be78066d04e5fd9e56
