### ISSUE TITLE
configurechains for Sepolia testnet with alchemyProvider 

### ISSUE THREAD

**Issue by MrVa55** [wagmi-dev/wagmi#2219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

@wagmi/chains version "0.2.19",

### Current Behavior

Trying to configure Sepolia with AlchemyProvider gives error "Error: unsupported network (argument="network", value={"name":"sepolia","chainId":11155111,"ensAddress":null}, code=INVALID_ARGUMENT, version=providers/5.7.2)". Page continuously reloads

Error doesn't happen with publicProvider or with other chains. 

### Expected Behavior

configuring sepolia to add to client without error

### Steps To Reproduce

import { sepolia } from '@wagmi/core/chains';
import { alchemyProvider } from 'wagmi/providers/alchemy'
const { provider, webSocketProvider } = configureChains([sepolia], [  alchemyProvider({ apiKey: process.env.NEXT_PUBLIC_ALCHEMY_API_KEY }) ]);

**Comment by derodero24** [comment]
Same with v0.12.12. Work around it by using v0.12.11.

**Comment by jxom** [comment]
Ethers v5 doesn't support Sepolia yet. Will need to use the `jsonRpcProvider` as a workaround and enter the URL manually.

**Comment by technophile-04** [comment]
> Ethers v5 doesn't support Sepolia yet. Will need to use the jsonRpcProvider as a workaround and enter the URL manually.

Tysm @jxom  🙌 

**Question**  :  Any reason why this breaks in [`0.12.0`](https://github.com/wagmi-dev/wagmi/releases/tag/wagmi%400.12.0) and not in  `0.11.7` (last 0.11.x version) ? 

Because I see even `0.11.x` was also using ethers `v5` . 

The reason why I said it breaks at `0.12.0` is because I tried incrementally upgrading `wagmi` version starting from `0.11.6` and it started breaking at [`0.12.0`](https://github.com/wagmi-dev/wagmi/releases/tag/wagmi%400.12.0). 

My assumption: In `0.11.x` it would go to the next `provider` provided in an array... in our case  its `publiProvider()` but  something was changed in  [`0.12.0`](https://github.com/wagmi-dev/wagmi/releases/tag/wagmi%400.12.0) which is breaking it, its not fallbacking

Thanks again 🙌
