### ISSUE TITLE
bug: Switching network then cancel doesn't throw user cancel error

### ISSUE THREAD

**Issue by michaelotis** [wagmi-dev/wagmi#2269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.12

### Current Behavior

Calling switchNetwork to a network that Metamask doesn't have, throws the same error as changing networks and clicking cancel on the network change. Thus if you're trying to catch the missing Metamask network and trigger an add, if a user executes a network switch, it will then attempt to add the network because the errors being thrown are the same, ChainNotConfiguredError.

### Expected Behavior

Either it should throw UserRejectedRequestError or SwitchChainError, not ChainNotConfiguredError so it can properly be caught and handled

### Steps To Reproduce

Call switchNetwork, catch ChainNotConfiguredError and execute a function to add a network. It will prompt the user to switch but if the user cancel's it will then prompt the user to add the network again with our network details, even though the user already has the network.

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

Specifically, the Connector you are using (`MetaMaskConnector` or `InjectedConnector`), chain you are trying to switch to, etc.
