### ISSUE TITLE
bug: @wagmi/core v1.0.2 -> fetchEnsAvatar

### ISSUE THREAD

**Issue by unicape** [wagmi-dev/wagmi#2326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.2

### Current Behavior

ContractFunctionExecutionError: The contract function "resolve" reverted with the following reason:
Array index is out of bounds.

Contract Call:
  address:   0xA292E2E58d4ddEb29C33c63173d0E8B7a2A4c62e
  function:  resolve(bytes name, bytes data)
  args:             (0x2a30783131646335373935336264396333633631626137356131383363373134306562366635393836366200, 0x59d1d43cc07224ba941b60be8539c6f2ac1d2b1c877695730b89869eceddffdeb1fc04c0000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000066176617461720000000000000000000000000000000000000000000000000000)

Docs: https://viem.sh/docs/contract/readContract.html
Version: viem@0.3.18
    at getContractError (getContractError.ts:55:10)
    at readContract (readContract.ts:100:11)
    at async getEnsText (getEnsText.ts:85:15)
    at async getEnsAvatar (getEnsAvatar.ts:57:18)
    at async fetchEnsAvatar (chunk-VEUO7GWU.js:2598:18)

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

Particularly, what does your `fetchEnsAvatar` call look like (e.g. ENS name, chain, RPC provider)?
