### ISSUE TITLE
bug: usePrepareContractWrite's status not reseting when refetching

### ISSUE THREAD

**Issue by danilo-89** [wagmi-dev/wagmi#2967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

Once the usePrepareContractWrite operation succeeds, the status remains unchanged; it consistently remains "success" and doesn't transition to "loading" even during ongoing refetching processes.

### Expected Behavior

When refetch is initiated status of usePrepareContractWrite hook should change to "loading" while refetching is in progress.

### Steps To Reproduce

- Connect with Metamask wallet
- Run "Refetch Prepare" once
- Run it again
- Watch for "Prepare status" not changing while refetch is in progress

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/next-typescript-ug1jme?file=components%2FCustom.tsx

**Comment by tmm** [comment]
Check out the [React Query docs](https://tanstack.com/query/v4/docs/react/reference/useQuery) on fetching status. `status` is `loading` if there's no cached data and no query attempt was finished yet. Since data was already fetched and there are no errors, `status` will continue to be `success`. You probably want `fetchStatus` instead.
