### ISSUE TITLE
[bug] Getting `Error: missing argument: passed to contract (count=0, expectedCount=1, code=MISSING_ARGUMENT, version=contracts/5.6.2)`

### ISSUE THREAD

**Issue by bigint** [wagmi-dev/wagmi#769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.0

### Current Behavior

This is happening on page load when using the new `usePrepareContractWrite` hook

![image](https://user-images.githubusercontent.com/69431456/181178317-ba97c226-a117-4931-ae01-cbe85f1dfc6a.png)

### Expected Behavior

Should not throw any error

### Anything else?

https://github.com/lensterxyz/lenster/pull/142

**Comment by sasicodes** [comment]
same 😞 https://github.com/sasicodes/lenstube/pull/253

**Comment by jxom** [comment]
Can you please provide a minimal reproducible example?

**Comment by tmm** [comment]
Looks like `usePrepareContractWrite` is missing an argument for the function you are trying to prepare. (My guess is because the argument isn't available on page load. Maybe we add an `enabled` option for prepare hooks.)

Like @jxom said: Please attach a minimal reproducible example and re-open so we can get to debugging!

**Comment by bigint** [comment]
This is fixed by adding `enabled: false` 👍🏻
