### ISSUE TITLE
useContractRead returns abi.map is not a function. While useContractReads works.

### ISSUE THREAD

**Issue by RielJ** [wagmi-dev/wagmi#886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.5.1

### Current Behavior

`useContractRead` Function returns `TypeError: abi.map is not a function`.

### Expected Behavior

 while `useContractReads` Successfully returns the said data. Which is the expected returned value with the same input arguments as `useContractRead`

### Steps To Reproduce

```ts
  const contract = {
    addressOrName: address,
    contractInterface: abi
  };

  const { data: borrowBalance } = useContractRead({
    ...contract,
    functionName: "borrowBalanceStored",
    args: address,
    chainId: chainId,
  });

  const { data } = useContractReads({
    contracts: [
      {
        ...contract,
        args: address,
        functionName: "borrowBalanceStored",
        chainId: chainId,
      },
    ],
  });
```

**Comment by jxom** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via a CodeSandbox (feel free to use [this template](https://codesandbox.io/s/bitter-wind-pv0hwj)) and reopen this issue. Other information is also helpful, like framework (e.g. Next.js), browser, etc.

**Comment by realsbd** [comment]
I got the same error while using useContractWrite function. Why is there no solution to this?

**Comment by tmm** [comment]
@realsbd We need a minimal reproducible example to look into it more. Feel free to add one.
