### ISSUE TITLE
bug: NextJs 12 Build Type Error

### ISSUE THREAD

**Issue by faillacec** [wagmi-dev/wagmi#887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.3

### Current Behavior

Nextjs build fail using wagmi implementation

Problem with type export in lib

Type error: ',' expected.
> 1 | export { connect, type ConnectArgs, type ConnectResult } from './connect';

<img width="766" alt="Screen Shot 2022-08-25 at 3 55 59 PM" src="https://user-images.githubusercontent.com/97037379/186756751-90920549-22e1-4e77-9c02-0087f66a2b99.png">

### Expected Behavior

Build Working

**Comment by jxom** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue. Other information is also helpful, like framework (e.g. Next.js), browser, etc.

Maybe also try remove your `node_modules` and `npm i` again.
