### ISSUE TITLE
bug: Can't find variable: getProvider - React Native using wagmi 0.64.0

### ISSUE THREAD

**Issue by thegitparticle** [wagmi-dev/wagmi#911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.64.0

### Current Behavior

While trying to setup WalletConnect Setup using wagmi 0.64.0 - It does not work and throws this error up -  Can't find variable: getProvider. 
![IMG_12AF1FAC4B8A-1](https://user-images.githubusercontent.com/12975157/188272376-f35e5cbb-b9fd-449c-86d4-8a0c9c877d01.jpeg)
![Uploading IMG_12AF1FAC4B8A-1.jpeg…]()

### Steps To Reproduce

Just use a fresh bare React native or expo project, wagmi 0,64.0 and try to setup WalletConnect connection. The build would succeed but App.js where you would wrap the entire project in wagmi and walletconnect contexts would crash to show this above error.

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

You can check out this [discussion thread on React Native](https://github.com/wagmi-dev/wagmi/discussions/533) to see if there's any helpful info there as well.

**Comment by thegitparticle** [comment]
Run this expo app - you can re produce the error. It persists even in the latest wagmi version.

Expo app repo to reproduce - https://github.com/thegitparticle/wagmi-rn-setup
