### ISSUE TITLE
bug: providers fallback not working

### ISSUE THREAD

**Issue by danilo-89** [wagmi-dev/wagmi#961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.6

### Current Behavior

When alchemyProvider fails there is no fallback to the next provider.

### Expected Behavior

On provider connection error it should fallback to next provider if it's available.

### Steps To Reproduce

- Open Minimal Reproducible Example.
- Check Console
- Following errors and messages show:
  - WebSocket connection to 'wss://eth-mainnet.ws.alchemyapi.io/v2/aNDkHz4qGHIDnHpeMnT552Y1lMCtsHXa' failed
  - Failed to load resource: the server responded with a status of 401
  - useContractReads hook from "index.js" returns empty array
 
 - Now comment line 19 in "_app.js" file `// alchemyProvider({ apiKey: alchemyId, priority: 0 }),` , rerun and check console again
 - No errors and useContractReads hook returns valid data

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://stackblitz.com/edit/nextjs-4tqzis?file=pages%2F_app.js

**Comment by jxom** [comment]
Hey! Thanks a lot for opening this issue! I did some digging, and it seems like this may be an issue with the ethers `FallbackProvider`. In the CodeSandbox below, you can see that this doesn't seem to work with a plain ethers `FallbackProvider` either:

https://codesandbox.io/s/jovial-dirac-vouhru

I am going to close this issue here and open up an issue on the ethers repo.
